### ISSUE TITLE
Bus and Train config incomplete error

### ISSUE THREAD

**Issue by ChaRRoss** [NateDee/MMM-CTA#5]
Hello Nate! I love the module idea and just started working with magic mirror. Unfortunately I can't seem to get the module to work with the API. I was able to test the keys and the bus and train stop IDs with url calls but it doesnt seem to want to work in the config.js. Attached I have a screen shot of my json with the log for magic mirror! Wondering if there's anything I got wrong! Thanks for your time and help!

**Comment by NateDee** [comment]
Hi, only issue I see is "config:" is misspelled as "conifg"

See if that fixes it.  I'm also going to delete your picture as it contains your API keys, which you don't want someone else abusing!

**Comment by ChaRRoss** [comment]
OH right thank you!

**Comment by ChaRRoss** [comment]
accidentally closed the issue. The bus stop now works however I still get an incomplete for the train. I'm thinking it may be an API key issue. Thank you though for getting back to me so quickly! Let me know if you have any thoughts on the matter! I'll be sure to let you know if I find a solution.

**Comment by NateDee** [comment]
Try trainStopID should be a trainStationID, that should be the error

**Comment by ChaRRoss** [comment]
It was. Sorry, those are pretty lazy mistakes!

**Comment by NateDee** [comment]
No worries, sometimes you just need a second pair of eyes to not go crazy.
